[tool.poetry]
name = "coriolis"
version = "0.1.0"
description = "Small event ticketing and management tool"
license = "AGPL-3.0-or-later"
authors = ["Ryszard Knop <rk@dragonic.eu>"]
repository = "https://github.com/DragoonAethis/Coriolis"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Environment :: Web Environment",
    "Framework :: Django",
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
sentry-sdk = "^1.5.5"
Django = "^3.2.11"
django-allauth = "^0.48.0"
django-environ = "^0.8.1"
django-debug-toolbar = "^3.2.4"
django-phonenumber-field = {extras = ["phonenumberslite"], version = "^6.1.0"}
django-crispy-forms = "^1.14.0"
crispy-bootstrap5 = "^0.6"
gunicorn = "^20.1.0"
whitenoise = {extras = ["brotli"], version = "^6.0.0"}
psycopg2 = "^2.9.3"
django-allauth-2fa = "^0.8"
django-colorfield = "^0.6.3"
Pillow = "^9.0.0"
Markdown = "^3.3.6"
django-payments = "^0.15.0"
django-money = "^2.1.1"
dramatiq = {extras = ["watch", "redis"], version = "^1.12.3"}
django-dramatiq = "^0.10.0"

# Commented out until fixes are upstreamed:
#django-payments-przelewy24 = "0.1.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
